# Generated by Django 6.0.5 on 2026-05-31 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('profesor', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nume'],
                'unique_together': {('user', 'nume')},
            },
        ),
        migrations.CreateModel(
            name='Absenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('motivata', 'Motivată'), ('nemotivata', 'Nemotivată')], default='nemotivata', max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('motiv', models.CharField(blank=True, max_length=200)),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absente', to='tracker.materie')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.FloatField()),
                ('descriere', models.CharField(blank=True, max_length=200)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='tracker.materie')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='StudyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('ore_studiu', models.CharField(choices=[('0', '0h'), ('0.5', '30min'), ('1', '1h'), ('1.5', '1.5h'), ('2', '2h'), ('2.5', '2.5h'), ('3', '3h+')], default='1', max_length=5)),
                ('productivitate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('intelegere', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('stres', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('user', 'data')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saptamana_start', models.DateField()),
                ('ce_a_mers', models.TextField(blank=True)),
                ('ce_a_fost_dificil', models.TextField(blank=True)),
                ('obiectiv', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflectii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saptamana_start'],
                'unique_together': {('user', 'saptamana_start')},
            },
        ),
    ]
